/*
 * This source file was generated by the Gradle 'init' task
 */
package org1.example1;

import java.util.HashMap;
import java.util.Scanner;

class Result{
    int x;
    double y;

}

class Calculator{
    public HashMap<Integer, String> options;
    public int SQRT = 1;
    public int FACTORIAL = 2;
    public int NATURAL_LOG = 3;
    public int POWER = 4;
    public Calculator(){
        options = new HashMap<>();
        this.options.put(SQRT, "sqrt");
        this.options.put(FACTORIAL, "factorial");
        this.options.put(NATURAL_LOG, "natural_log");
        this.options.put(POWER, "power");
    }
    public double sqrt(double x){
        return Math.sqrt(x);
    }

    public int factorial(int x){
        int ans = 1;
        for(int i=1; i<=x; i++){
            ans *= i;
        }
        return ans;
    }

    public double natural_log(double a){
        return Math.log(a);
    }

    public double power(double a, double b){
        return Math.pow(a, b);
    }
    public void printMenuOptions() {
        System.out.println("Enter one of the numbers below to continue.\nPress any other number to exit");
        for (Integer key : this.options.keySet()) {
            String value = this.options.get(key);
            System.out.printf("%d %s\n", key, value);
        }
        System.out.print("\n");
    }
}

public class App {
    //sqrt, factorial, natural log and power

    public static void main(String[] args) {
        Calculator calc = new Calculator();
        Scanner sc = new Scanner(System.in);
        while(true){
            calc.printMenuOptions(); // Create a Scanner object
            System.out.print("Enter option: ");
            int option =  sc.nextInt();
            if(option == calc.SQRT){
                System.out.println("Enter the number: ");
                double val = sc.nextDouble();
                double result = calc.sqrt(val);
                System.out.printf("Your result is %f\n", result);
            }
            else if(option == calc.FACTORIAL){
                System.out.println("Enter a non negative integer: ");
                int val = sc.nextInt();
                int result = calc.factorial(val);
                System.out.printf("Your result is %d\n", result);
            }
            else if(option == calc.NATURAL_LOG){
                System.out.println("Enter the number: ");
                double val = sc.nextDouble();
                double result = calc.natural_log(val);
                System.out.printf("Your result is %f\n", result);
            }
            else if(option == calc.POWER){
                System.out.println("Enter the base: ");
                double base = sc.nextDouble();
                System.out.println("Enter the exponent: ");
                double exponent = sc.nextDouble();
                double result = calc.power(base ,exponent);
                System.out.printf("Your result is %f\n", result);
            }
            else{
                break;
            }
            System.out.println("------------------------------\n");

        }

    }
}
