/*
 * This source file was generated by the Gradle 'init' task
 */
package org1.example1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Calculator classUnderTest = new Calculator();

    }
}
